---
- name: reset virtual machine to clean slate
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: stop existing service if present
      service:
        name: fibd
        state: stopped
      ignore_errors: True
    - name: stop running daemon if running
      command: killall fibd
      ignore_errors: True
    - name: remove lock file if present
      file:
        path: /var/run/fibd.pid
        state: absent
